name: habit_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_analytics: ^10.8.8
  sentry_flutter: ^7.17.0 
  
  fl_chart: ^0.64.0
  flutter_local_notifications: ^16.3.2
  table_calendar: ^3.0.9
  confetti: ^0.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  google_sign_in: ^6.2.1

  supabase_flutter: ^2.5.0
  

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: habitflow-app
